name: SMP API Deploy

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy to Production
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: barengsaya.com
          REMOTE_USER: bare3321
          TARGET: /home/bare3321/api.smp
          SCRIPT_AFTER: |
            cd /home/bare3321/api.smp
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan optimize
            chmod -R 775 storage bootstrap/cache
